# Generated by Django 2.0.5 on 2018-05-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cod_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=40)),
                ('nome_prop', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tipo_fornecedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('cod_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('desc_produto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cod_fornecedeor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.Fornecedor')),
            ],
        ),
    ]
